const canBetNpb = [
  {
    matchDate: "03/29",
    matchTime: "14:00",
    category: "NPB",
    homeTeam: "巨人",
    awayTeam: "阪神",
    avenue: "東京ドーム",
    oddsHome: 1.82,
    oddsDraw: 7.8,
    oddsAway: 3.29,
    canBet: "after",
    type: "セ・リーグ",
  },
  {
    matchDate: "03/29",
    matchTime: "16:00",
    category: "NPB",
    homeTeam: "広島",
    awayTeam: "横浜",
    avenue: "マツダスタジアム",
    oddsHome: 2.65,
    oddsDraw: 10.82,
    oddsAway: 1.14,
    canBet: "now",
    type: "セ・リーグ",
  },
  {
    matchDate: "03/29",
    matchTime: "16:00",
    category: "NPB",
    homeTeam: "ヤクルト",
    awayTeam: "中日",
    avenue: "神宮球場",
    oddsHome: 1.53,
    oddsDraw: 5.67,
    oddsAway: 3.34,
    canBet: "now",
    type: "セ・リーグ",
  },
  {
    matchDate: "03/29",
    matchTime: "18:00",
    category: "NPB",
    homeTeam: "ソフトバンク",
    awayTeam: "オリックス",
    avenue: "PayPayドーム",
    oddsHome: 1.24,
    oddsDraw: 6.78,
    oddsAway: 2.79,
    canBet: "now",
    type: "パ・リーグ",
  },
  {
    matchDate: "03/29",
    matchTime: "18:00",
    category: "NPB",
    homeTeam: "日本ハム",
    awayTeam: "楽天",
    avenue: "札幌ドーム",
    oddsHome: 3.45,
    oddsDraw: 6.89,
    oddsAway: 1.44,
    canBet: "now",
    type: "パ・リーグ",
  },
  {
    matchDate: "03/29",
    matchTime: "18:00",
    category: "NPB",
    homeTeam: "ロッテ",
    awayTeam: "西武",
    avenue: "ZOZOマリンスタジアム",
    oddsHome: 3.45,
    oddsDraw: 7.98,
    oddsAway: 1.21,
    canBet: "now",
    type: "パ・リーグ",
  },

  {
    matchDate: "03/30",
    matchTime: "16:00",
    category: "NPB",
    homeTeam: "オリックス",
    awayTeam: "ソフトバンク",
    avenue: "PayPayドーム",
    oddsHome: 1.23,
    oddsDraw: 8.4,
    oddsAway: 2.58,
    canBet: "before",
    type: "パ・リーグ",
  },
];

export { canBetNpb };
